version: "3.7"

services:
  mytwitterapi:
    container_name: my-twitter-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./node_modules:/app/node_modules"
      - "./src:/app/src"
    expose: [3001]
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MYSQL_HOST=my-twitter-db
      - MYSQL_PORT=3306
      - MYSQL_USER_NAME=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mytwitter
      - JWT_KEY=secret-key
      - MINIO_ROOT_HOST=my-twitter-minio
      - MINIO_API_PORT=9000
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  mysql:
    image: mysql
    container_name: my-twitter-db
    expose: [3307]
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mytwitter

  minio:
    image: quay.io/minio/minio
    container_name: my-twitter-minio
    command: server /data --console-address ":9001"
    volumes:
      - D:\data:/data
    expose: [9000, 9001]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
